version: '3.5'

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    networks:
      - streams-network
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-enterprise-kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - streams-network
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "drone-report:1:1,connect-config:1:1,connect-offset:1:1,connect-status:1:1"

  schema-registry:
    image: "confluentinc/cp-schema-registry:latest"
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    networks:
      - streams-network
    hostname: schema-registry
    restart: on-failure
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

  minio:
    image: minio/minio:latest
    ports:
        - 9000:9000
        - 9001:9001
    networks:
        - streams-network
    hostname: minio
    command: server /data --console-address ":9001"
    environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin

  create-buckets:
      image: minio/mc
      depends_on:
          - minio
      networks:
        - streams-network
      hostname: create-buckets
      entrypoint: >
          /bin/sh -c -e "
          until (/usr/bin/mc alias set myminio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
          /usr/bin/mc mb -p myminio/kafka-bucket;
          /usr/bin/mc policy set public myminio/kafka-bucket;
          "

  kafka-connect:
    image: "confluentinc/cp-kafka-connect:latest"
    networks:
        - streams-network
    hostname: kafka-connect
    depends_on:
      - kafka
      - schema-registry
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: srvc_connect
      CONNECT_CONFIG_STORAGE_TOPIC: connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offset
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_PLUGIN_PATH: /usr/share/java/confluentinc/cp-kafka-connect:7.1.1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.avro.AvroConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.avro.AvroConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.avro.AvroConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect

networks:
  streams-network:
