version: '3.5'

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:7.1.0"
    hostname: zookeeper
    networks:
      - peace-project-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: nc -vz localhost 2181
      interval: 5s
      timeout: 30s
      retries: 5

  kafka:
    image: "confluentinc/cp-enterprise-kafka:7.1.0"
    hostname: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - peace-project-net
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "drone-report:1:1"
    healthcheck:
      test: nc -vz localhost 9092
      interval: 5s
      timeout: 30s
      retries: 5

  schema-registry:
    image: "confluentinc/cp-schema-registry:7.1.0"
    depends_on:
      kafka:
        condition: service_healthy
    hostname: schema-registry
    ports:
      - 8081:8081
    networks:
      - peace-project-net
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    healthcheck:
      test: curl --fail http://schema-registry:8081/
      interval: 5s
      timeout: 30s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2022-06-07T00-33-41Z.fips
    ports:
        - 9000:9000
        - 9001:9001
    networks:
      - peace-project-net
    command: server /data --console-address ":9001"
    environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: curl http://minio:9000
      interval: 3s
      timeout: 30s
      retries: 5

  create-buckets:
      image: minio/mc:RELEASE.2022-05-09T04-08-26Z
      depends_on:
        minio:
          condition: service_healthy
      networks:
      - peace-project-net
      entrypoint: >
          /bin/sh -c -e "
          until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
          /usr/bin/mc mb -p myminio/kafka-bucket;
          /usr/bin/mc policy set public myminio/kafka-bucket;
          "

  kafka-connect:
    image: srvc_connect
    build: srvc_connect
    depends_on:
      create-buckets:
        condition: service_started
      schema-registry:
        condition: service_healthy
    ports:
      - 8083:8083
    networks:
      - peace-project-net
    healthcheck:
      test: "curl --fail http://srvc_connect:8083/connectors"
      interval: 3s
      timeout: 30s
      retries: 5
    environment:
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: srvc_connect
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost

      CONNECT_CONFIG_STORAGE_TOPIC: connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offset
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter

      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components

  srvc_drone:
    image: srvc_drone
    build: .
    depends_on:
      kafka-connect:
        condition: service_started
    networks:
      - peace-project-net
    command: /ops/sbt/bin/sbt "project srvc_drone" run

  srvc_analysis:
    image: srvc_analysis
    build: .
    depends_on:
      kafka-connect:
        condition: service_started
    networks:
      - peace-project-net
    command: /ops/sbt/bin/sbt "project srvc_analysis" run

  srvc_alert:
    image: srvc_alert
    build: .
    depends_on:
      kafka-connect:
        condition: service_started
    networks:
      - peace-project-net
    command: /ops/sbt/bin/sbt "project srvc_alert" run

  srvc_back:
    image: srvc_back
    build: .
    ports:
      - 8080:8080
    networks:
      - peace-project-net
    command: /opt/sbt/bin/sbt "project srvc_back" run
networks:
  peace-project-net:
