version: '3.5'

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    hostname: zookeeper
    networks:
      - peace-project-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-enterprise-kafka:latest"
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - 9092:9092
    networks:
      - peace-project-net
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "drone-report:1:1"

  schema-registry:
    image: "confluentinc/cp-schema-registry:latest"
    depends_on:
      - kafka
    hostname: schema-registry
    ports:
      - 8081:8081
    networks:
      - peace-project-net
    restart: on-failure
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

  minio:
    image: minio/minio:latest
    ports:
        - 9000:9000
        - 9001:9001
    networks:
      - peace-project-net
    command: server /data --console-address ":9001"
    environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin

  create-buckets:
      image: minio/mc
      depends_on:
          - minio
      networks:
      - peace-project-net
      entrypoint: >
          /bin/sh -c -e "
          until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
          /usr/bin/mc mb -p myminio/kafka-bucket;
          /usr/bin/mc policy set public myminio/kafka-bucket;
          "

  kafka-connect:
    image: srvc_connect
    build: srvc_connect
    depends_on:
      - schema-registry
      - create-buckets
    ports:
      - 8083:8083
    networks:
      - peace-project-net
    environment:
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: srvc_connect
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost

      CONNECT_CONFIG_STORAGE_TOPIC: connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offset
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: schema-registry:8081

      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter

      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components

  srvc_drone:
    image: srvc_drone
    build: .
    depends_on:
      - schema-registry
    networks:
      - peace-project-net
    command: /ops/sbt/bin/sbt "project srvc_drone" run

  srvc_analysis:
    image: srvc_analysis
    build: .
    depends_on:
      - kafka-connect
    networks:
      - peace-project-net
    command: /ops/sbt/bin/sbt "project srvc_analysis" run

  srvc_alert:
    image: srvc_alert
    build: .
    depends_on:
      - srvc_drone
    networks:
      - peace-project-net
    command: /ops/sbt/bin/sbt "project srvc_alert" run

networks:
  peace-project-net:
