version: '3.5'

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    networks:
      - streams-network
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    ports:
      - 9092:9092
    networks:
      - streams-network
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "drone-report:1:1"

  schema-registry:
    image: "confluentinc/cp-schema-registry:latest"
    ports:
      - 8081:8081
    networks:
      - streams-network
    hostname: schema-registry
    restart: on-failure
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

networks:
  streams-network: